### ISSUE TITLE
Could not load next train

### ISSUE THREAD

**Issue by dsa146** [amandeepg/PathTimes#1]
Hello,

I love this app and since 08/24 it gave me the error when opening and I cannot view the Path time as usual. Please update
![Screenshot_2024-08-24-13-24-39-396](https://github.com/user-attachments/assets/7225540f-9e04-4842-8176-66b2f2354c5e)

**Comment by amandeepg** [comment]
Hi there, this was an issue with the API I use, along with all the other third-party apps. It should be working again now however
